### ISSUE TITLE
Why we need depth image for inference ?

### ISSUE THREAD

**Issue by delldu** [Ephemeral182/UWNR#1]
Dear friends,
    Thanks for your good work !
    As title, we found this work need depth image for generating stage, why ?
    Best regards,

**Comment by Ephemeral182** [comment]
We adopt depth map to catch depth information,  just like transmission map which consists of depth map in physics formulas.

**Comment by delldu** [comment]
Thanks a lot.

**Comment by delldu** [comment]
Thanks
